name       : translate-shell
version    : 0.9.6.8
release    : 6
source     :
    - https://github.com/soimort/translate-shell/archive/v0.9.6.8.tar.gz : 3cfdd5be799859465fc6b96e8fbd880a881395ae12c0e83be7a72434f914cc9f
license    : Unlicense
component  : office
summary    : A command-line online translator
description: |
    Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate and Apertium.
builddeps  :
    - rlwrap  # check
    - emacs   # check
rundeps    :
    - fribidi
    - rlwrap
setup      : |
    # curl tests fails on Solus
    %patch -p1 < $pkgfiles/0001-Remove-curl-tests.patch
    %patch -p1 < $pkgfiles/0002-Stop-building-everywhere.patch
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX%
check      : |
    export LC_ALL=en_US.utf8
    %make test
