name       : translate-shell
version    : 0.9.6.11
release    : 8
source     :
    - https://github.com/soimort/translate-shell/archive/v0.9.6.11.tar.gz : 589505248212726dff2b3e8828514036491f019fcee8657c0d94bb1a5dac6c5b
license    : Unlicense
component  : office
summary    : A command-line online translator
description: |
    Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate and Apertium.
builddeps  :
    - emacs   # check
    - rlwrap  # check
rundeps    :
    - fribidi
    - rlwrap
setup      : |
    # curl tests fails on Solus
    %patch -p1 < $pkgfiles/0001-Remove-curl-tests.patch
    %patch -p1 < $pkgfiles/0002-Stop-building-everywhere.patch
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX%
check      : |
    %make test
