name       : translate-shell
version    : 0.9.6.12
release    : 9
source     :
    - https://github.com/soimort/translate-shell/archive/v0.9.6.12.tar.gz : 4c4843a8c66276190535b8435775ecb5d9c8286083a33cdbe2db608eba93ca97
license    : Unlicense
component  : office
summary    : A command-line online translator
description: |
    Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate and Apertium.
builddeps  :
    - emacs   # check
    - rlwrap  # check
rundeps    :
    - fribidi
    - rlwrap
setup      : |
    # curl tests fails on Solus
    %patch -p1 < $pkgfiles/0001-Remove-curl-tests.patch
    %patch -p1 < $pkgfiles/0002-Stop-building-everywhere.patch
build      : |
    %make
install    : |
    %make_install PREFIX=%PREFIX%
check      : |
    %make test
