name       : translate-shell
version    : 0.9.6.5
release    : 2
source     :
    - https://github.com/soimort/translate-shell/archive/v0.9.6.5.tar.gz : 6d9ae244e6dbf42466dec00dd0b955659ba275d7e780bbd101c27c9325d413ef
license    : Unlicense
component  : office
summary    : A command-line online translator
description: |
    Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate and Apertium.
rundeps    :
    - fribidi
    - rlwrap
build      : |
    #Split build and install in 2 different steps
    sed -i 's|install: build|install:|' Makefile
    %make
install    : |
    %make_install PREFIX=/usr
