name       : translate-shell
version    : 0.9.6.7
release    : 5
source     :
    - https://github.com/soimort/translate-shell/archive/v0.9.6.7.tar.gz : 25f90bd755b457602928d4efbdd8db64129013f2943d1d9c1316c6854736db46
license    : Unlicense
component  : office
summary    : A command-line online translator
description: |
    Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate and Apertium.
builddeps  :
    - rlwrap  # check
    - emacs   # check
rundeps    :
    - fribidi
    - rlwrap
setup      : |
    # curl tests fails on Solus
    %patch -p1 < $pkgfiles/0001-Remove-curl-tests.patch
    %patch -p1 < $pkgfiles/0002-Stop-building-everywhere.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
check      : |
    export LC_ALL=en_US.utf8
    %make test
