name       : translate-shell
version    : 0.9.6.6
release    : 3
source     :
    - https://github.com/soimort/translate-shell/archive/v0.9.6.6.tar.gz : ff7809d464b30f97260e65cc94e76fe826646d18cb5be133243eebf06c9a3295
license    : Unlicense
component  : office
summary    : A command-line online translator
description: |
    Translate Shell (formerly Google Translate CLI) is a command-line translator powered by Google Translate (default), Bing Translator, Yandex.Translate and Apertium.
builddeps  :
    - rlwrap  # check
    - emacs   # check
rundeps    :
    - fribidi
    - rlwrap
setup      : |
    # curl tests fails on Solus
    %patch -p1 < $pkgfiles/0001-Remove-curl-tests.patch
    %patch -p1 < $pkgfiles/0002-Stop-building-everywhere.patch
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
check      : |
    export LC_ALL=en_US.utf8
    %make test
